---
title: "HW #8"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "7 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "4.3.3, 4.3.11, 4.3.13"
misc: "4.4.1, 4.4.5, 4.4.6ab"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.3.3}

a) Supply a proof for Theorem 4.3.9 using the $\epsilon-\delta$ characterization of continuity. 

\begin{solution}
The theorem states: If $f$ is continuous at $c \in A$, and if $g$ is continuous at $f(c) \in B$, then $g(f(c))$ is continuous at $c$. \\

Since $g$ is continuous at $f(c)$ it can be said that whenever $|f(x) - f(c) < \delta$ it follows that $|g(f(x)) - g(f(c))| < \epsilon$. This means that $g(f(x))$ is continuous at $c$ whenever $|x-c| \delta$.   
\end{solution}


b) Give another proof of this theorem using the sequential characterization of continuity (thm 4.3.2 iii).

\begin{solution}
thm 4.3.2 iii) states: For all $(x_n) \to c$ (with $x_n \in A$), it follows that $f(x_n) \to f(c)$. 

Since $g$ is continuous at $f(c)$ it can be said that, for all $(f(x_n)) \to f(c)$ (with $f(x_n) \in B$), it follows that $g(f(x_n)) \to g(f(c))$. This means that $g(f(x))$ is continuous at $c$.
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.3.11} 

(CONTRACTION MAPPING THEOREM) Let $f$ be a function defined on all of $\mathbb{R}$, and assume there is a constant $c$ such that $0 < c < 1$ and 
$$
|f(x) - f(y)| \le c|x-y|
$$
for all $x,y \in \mathbb{R}$.

a) Show that $f$ is continuous on $\mathbb{R}$.

\begin{solution}
Let $\delta = \epsilon/c$, where $epsilon > 0$. \\

Whenever $|x-y| < \delta$ it follows that

$$
\begin{aligned}
|x-y| &< \epsilon/c  \\
c|x-y| &< \epsilon  \\
|f(x) - f(y)| \le c|x-y| &< \epsilon \\
|f(x) - f(y)| &< \epsilon
\end{aligned}
$$
Thus $f$ is continuous by definition of continuity.  
\end{solution}

b) Pick some point $y_1 \in \mathbb{R}$ and construct the sequence
$$
(y_1, f(y_1), f(f(y_1)),...).
$$
In general, if $y_{n+1} = f(y_n)$, show that the resulting sequence $(y_n)$ is a Cauchy sequence. Hence we may let $y=\lim y_n$.

\begin{solution}
To show that the sequence is Cauchy, I must show that there exist an $N$ such that whenever $m,n \ge N$ it follows that $|a_n - a_m| < \epsilon$.

Let $y_{n+1} = f(y_n)$ and pick some arbitrary $y_1$ within $\mathbb{R}$. Given $|f(x) - f(y)| \le c|x-y|$, it follows that

$$
\begin{aligned}
|f(y_1) - f(y_2)| &\le c|y_1 - y_2| \\
|y_2 - y_3| &\le c|y_1 - y_2|
\end{aligned}
$$
It is also true that  

$$
|y_3 - y_4| \le c|y_2 - y_3|
$$

Then since $0 < c < 1$

$$
|y_3 - y_4| < c|y_2 - y_3| \le c^2|y_1 - y_2|
$$
Staying with the same pattern it can be said that 

$$
|y_n - y_{n+1}| < c^{n-1}|y_1 - y_2| \ \ \  \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \  (1)
$$
The right side will get closer to 0. 
\end{solution}

\begin{solution}
This is not enough to prove that the sequence is Cauchy because I need to show that I can choose any $n,m > N$.\\

Let $n,m > N$. Consider the following,

$$
|y_N - y_m| = |y_N - y_{N+1} + y_{N+1} - ... - y_{m-1} + y_{m-1}- y_m|
$$
Then using the inequality above (1), 

$$
|y_N - y_{N+1} + y_{N+1} - ... - y_{m-1} + y_{m-1}- y_m| \le ||y_N - y_{N+1}| + c|y_N - y_{N+1}| +...+ c^{m-2}|y_N- y_{N+1}|| 
$$
After using the triangle inequality theorem,

$$
\begin{aligned}
|y_N - y_m| &< (|y_N - y_{N+1}| + c|y_N - y_{N+1}| +...+ c^{m-2}|y_N - y_{N+1}|) \\
|y_N - y_m| &< (1 + c + c^2 + ... + c^{m-2})|y_N - y_{N+1}|
\end{aligned}
$$
Every $c$ can be summed using a geometric formula. But the finite sum will be less than the infinite sum so I write the above inequality as the following,

$$
|y_N - y_m| < \frac{|y_N - y_{N+1}|}{1-c}
$$
It can also be said that 

$$
|y_N - y_n| < \frac{|y_N - y_{N+1}|}{1-c}
$$

Consider

$$
\begin{aligned}
|y_n - y_m| &= |y_n - y_N + y_N - y_m| \le |y_N - y_n| + |y_N - y_m| \\
|y_n - y_m| &< \frac{|y_N - y_{N+1}|}{1-c} + \frac{|y_N - y_{N+1}|}{1-c} \\
|y_n - y_m| &< \frac{2c^{N-1}|y_1 - y_2|}{1-c}
\end{aligned}
$$

$$
\begin{aligned}
\frac{2c^{N-1}|y_1 - y_2|}{1-c} &= \epsilon \\
c^{N-1} &= \frac{\epsilon(1-c)}{2|y_1-y_2|} 
\end{aligned}
$$
Thus,
$$
N = \lfloor \frac{\ln \left( \frac{\epsilon(1-c)}{2|y_1-y_2|} \right)}{\ln(c)} \rfloor + 1
$$
Let $\epsilon > 0$. Thus choose an $N$ such that $m,n > N$ it follows that 

$$
|y_n - y_m| < \frac{2|y_N - y_{N+1}|}{1-c} < \frac{2c^{N-1}|y_1 - y_2|}{1-c} = \epsilon \\
$$
\end{solution}

\newpage

c) Prove that $y$ is a fixed point of $f$ (i.e., $f(y) = y$) and that it is unique in this regard.

\begin{solution}
Because the sequence is Cauchy we know that it converges to $y$. Also note that the function is continuous on its domain and is a recursive dynamical sequence. So the sequence $(y_1, f(y_1), f(f(y_1)),...) = (y, f(y), f(f(y),...) = (y,y,f(y),...) = (y,y,y,...)$ is obviosuly covnerging to $y$.   
\end{solution}

d) Finally, prove that if $x$ is any arbitrary point in $\mathbb{R}$, then the sequence $(x f(x), f(f(x)),...)$ converges to $y$ defined in (b). 

\begin{solution}
Since the function is continuous on all of $\mathbb{R}$ and converges to a point, $y$, then it must be true that any starting point on the real number line will lead the sequence to converge to $y$.
\end{solution}


\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.3.13}

Let $f$ be a function defined on all of $\mathbb{R}$ that satisfies the additive condition $f(x+y) = f(x) + f(y)$ for all $x,y \in \mathbb{R}$.

a) Show that $f(0) = 0$ and that $f(-x) = -f(x)$ for all $x \in \mathbb{R}$.


\begin{solution}
Let $f(a) = c$ \\

Because $f(x+y) = f(x) + f(y)$, the only way for a sum of two functions to be zero is if $c$ is already zero, or if $c$ was added with its inverse, $-c$. \\

Thus if $f(a) = c$ then it must be true that $f(-a) = -c$ because $f(a - a) = c + (-c) = 0 = f(0)$. 
\end{solution}

b) Let $k = f(1)$. Show that $f(n) = kn$ for all $n \in \mathbb{N}$, and then prove that $f(z) = kz$ for all $z \in \mathbb{Z}$. Now, prove that $f(r) = kr$ for any rational number $r$. 

\begin{solution}
I know that $f(1) = k$ and its also true that $f(1) + f(1) = k + k = 2k$. \\

If $f(n) = nk$ then it follows that 
$$
f(n) + f(1) = nk + k
$$

Then using the function's additive property,

$$
f(n+1) = (n+1)k
$$
Thus through induction, $f(n) = nk$ will be true for all $n \in \mathbb{N}$. \\

The exact same logic works for $f(z) = kz$. The only thing left to prove is that this works for the negative integers. \\

However, we know that $f(-n) = -nk$, thus $f$ can map to $\mathbb{Z}$.\\

To prove that $f(r) = kr$ consider the following,
$$
\begin{aligned}
f(1) = f(\sum^n(1/n)) &= k\\
\sum^n f(1/n) &= k \\
nf(1/n) &= k \\
f(1/n) &= k/n \\
f(m/n) &= \frac{mk}{n} \\
f(r) = rk
\end{aligned}
$$
\end{solution}

c) Show that if $f$ is continuous at $x=0$, then $f$ is continuous at every point in $\mathbb{R}$ and conclude that $f(x) = kx$ for all $x \in \mathbb{R}$. Thus, any additive function that is continuous at $x = 0$ must necessarily be a linear function through the origin.

\begin{solution}
Let $f(x) = kx$ and $\delta = \epsilon/k > 0$. We already know that When ever $|x - c| < \delta$ it follows that 

$$
\begin{aligned}
|x - c| < \epsilon / k \\
|kx - kc| < \epsilon \\
|f(x) - f(c)| < \epsilon
\end{aligned}
$$


\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.4.1}

a) Show that $f(x) = x^3$ is continuous on all $\mathbb{R}$.

\begin{solution}
I know that $x$ is continuous on all $\mathbb{R}$. I can use the algebraic continuity theorem (iii) to show that $x \cdot x \cdot x = x^3$ is also continuous.  
\end{solution}

b) Argue, using them 4.4.5, that $f$ is not uniformly continuous on $\mathbb{R}$.

\begin{solution}

\end{solution}

c) Show that $f$ is uniformly continuous on any bounded subset of $\mathbb{R}$.

\begin{solution}
x<1
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 05 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.4.5}

Assume that $g$ is defined on an open interval $(a,c)$ and it is known to be uniformly continuous on $(a,b]$ and $[b,c)$, where $a<b<c$. Prove that $g$ is uniformly continuous on $(a,c)$.

\begin{solution}
$g$ is uniformly continuous given that $x,y \in (a,b]$. $g$ is also uniformly continuous given that $x,y \in [b,c)$. But we don't know that $g$ is uniformly continuous that when $x \in (a,b]$ and $y \in [b,c)$. \\

Let $\epsilon /2 > 0$. Let $|g(x) - g(b)| < \epsilon/2$, given that $x \in (a,b]$. Further, let $|g(y) - g(b)| < \epsilon/2$, given that $y \in [b,c)$. \\

$$
\begin{aligned}
|g(x) - g(b)| + |g(y) - g(b)| &< \epsilon/2 + \epsilon/2 \\
|g(x) - g(y)| \le |g(x) - g(b)| + |g(y) - g(b)| &< \epsilon \\
|g(x) - g(y)| &< \epsilon
\end{aligned}
$$
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 06 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.4.6ab}

Give an example of each of the following, or state that such a request is impossible. for any that are impossible, supply a short explanation for why this is the case. 

a) A continuous function $f : (0,1) \to \mathbb{R}$ and a Cauchy sequence $(x_n)$ such that $f(x_n)$ is not a Cauchy sequence. 

\begin{solution}
True. Consider $y = \cot(\pi x)$ will map $(0,1) \to \mathbb{R}$, and if $x_n = \frac{1}{2n}$. \\

Here we see that $x_n$ is Cauchy, however, as the sequence gets closer to zero then $f(x_n)$ will get infinitely large, meaning it diverges. 
\end{solution}

b) A uniformly continuous function $f : (0,1) \to \mathbb{R}$ and a Cauchy sequence $(x_n)$ such that $f(x_n)$ is not a Cauchy sequence. 

\begin{solution}
This is false. No continuous function that maps $(0,1) \to \mathbb{R}$ is uniformaly continuous. 
\end{solution}

