---
title: "Homework 6"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "6.0 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "3.3.2abcd, 3.3.3, 3.3.5abc"
misc: "3.3.11, 3.4.1, 3.4.4ab"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.3.2 abcd}

Decide which of the following sets are compact. For those that are not compact, show how Definition 3.3.1 breaks down. In other words, give an example of a sequence contained in the given set that does not possess a subsequence converging to a limit in the set. 

a) $\mathbb{N}$

\begin{solution}
The set is not compact. The subsequence $\{ 1,3,5,...\}$ is contained in $\mathbb{N}$ but it does not converge to a limit. 
\end{solution}

b) $\mathbb{Q} \cap [0,1]$

\begin{solution}
The set is not compact.

$$
A = \{ \frac{1}{6} + \frac{1}{6 \cdot 2^2} + \frac{1}{6 \cdot 3^2} + . . . + \frac{1}{6 \cdot n^2} : n \in \mathbb{N}\}, \text{where}  
$$

$$
\lim A = \frac{\pi^2}{36} 
$$
The limit is within the bounds but is not a rational number. 

\end{solution}

c) The Cantor set

\begin{solution}
The set is compact.
\end{solution}

d) $\{1 + 1/2^2 + 1/3^2 +...+ 1/n^2 : n \in \mathbb{N} \}$

\begin{solution}
The set is not compact. Let the sequence be
$$
A = \{ 1 + \frac{1}{2^2} + \frac{1}{3^2} +...+ \frac{1}{n^2} : n \in \mathbb{N}\}, \text{where} 
$$
Where $\lim A = \frac{\pi^2}{6}$, but the limit is not in the set. 
\end{solution}


\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.3.3}

Prove the converse of theorem 3.3.4 by showing that if a set $K \subseteq \mathbb{R}$ is closed and bounded then it is compact.

\begin{solution}
Since $K$ is bounded every sequence in $K$ will also be bounded. By the Bolzano Weierstass theorem, every bounded sequence will contain a convergent subsequence. Theorem 3.2.5 states that these subsequences in $A$ converge to the limit points of $A$.\\

Those subsequence will converge to a limit within $K$ because the set is closed and contains its limit points, thus the assumptions of compactness is met.    
\end{solution}


<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.3.5 abc}

Decide whether the following propositions are true or false. If the claim is valid, supply a short proof, and if the claim is false, provide a counterexample. 

a) The arbitrary intersection of compact sets is compact. 

\begin{solution}
This is true. Theorem 3.2.14 says that the intersection of an arbitrary collection of closed sets is closed. Since compact sets are closed, the intersection of them would also be closed. \\

Compact sets are also bounded so the intersection of a bounded sets will still be bounded. Therefore the intersection will be compact.   
\end{solution}

b) The arbitrary union of compact sets is compact.

\begin{solution}
This is false. Theorem 3.2.14 says that the union of a finite collection of closed sets is closed. If a had the collection of sets $\mathbb{F} = \{[-n,n] : n \in \mathbb{N} \}$. This would work for a finite union, but the union of an arbitrary collection will not be bounded, therefore, it cannot be compact. 
\end{solution}

c) Let $A$ be arbitrary, and let $K$ be compact. Then, the intersection $A \cap K$ is compact. 

\begin{solution}
This is false. Consider $\mathbb{Q} \cap [0,1]$. $\mathbb{Q}$ is the arbitrary set $A$, and $K = [0,1]$ is the compact set. The intersection is not compact. 
\end{solution}



\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.3.11}

Consider each of the sets listed in Exercise 3.3.2. For each one that is not compact, find an open cover for which there is no finite subcover. 

a) $\mathbb{N}$

\begin{solution}
$\mathbb{F} = \{(0,n+2) : n \in \mathbb{N} \}$ \\
For this open cover to contain $\mathbb{N}$ it must infinite.
\end{solution}

b) $\mathbb{Q} \cap [0,1]$

\begin{solution}
$\mathbb{F} = \{ ( \frac{1}{n},1 + \frac{1}{n} ) : n \in \mathbb{N} \}$
\end{solution}


c) $\left( -1, \frac{ \sqrt{2} }{2} - \frac{1}{n} \right) \cup \left( \frac{\sqrt{2}}{2} + \frac{1}{n}, 2 \right)$

\begin{solution}
$\mathbb{F} = \{ \left( 0, \frac{\pi^2}{6} - \frac{1}{n} \right) \ : n \in \mathbb{N} \}$
\end{solution}


<!------------------------------------------------------------------------------>
<!------------------------------- Question 05 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.4.1}

If $P$ is a perfect set and $K$ is compact, is the intersection $P \cap K$ always compact? Always perfect?

\begin{solution}
If the perfect set were $P = [0,5]$ and the compact set were $K = \{1,2,3,4,5\}$. The intersection of these two results in $P \cap K = \{1,2,3,4,5\}$. As stated previously, theorem 3.2.14 implies that the intersection of any two closed sets will always be closed. \\

Any element within the intersection will be also exists in $K$ and $P$. Since $K$ and $P$ are bounded, the elements of the intersection will also be bounded. Those the intersection is compact.

However, in this case $P \cap K$ contains isolated points. So it is not true that the intersection will always be perfect.      
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 06 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.4.4}

Repeat the Cantor construction from Section 3.1 starting with the interval $[0,1]$. This time, however, remove the open middle fourth from each of the component. 

a) Is the resulting set compact? Perfect?

\begin{solution}
I can define the cantor set as the following,

$$
\begin{aligned}
C_0 &= [0,1] \\
C_1 &= \left[ 0, \frac{3}{8} \right] \cup \left[ \frac{5}{8},1  \right] \\
C_2 &= \left[ 0, \frac{3}{8} \right] \cup \left[] \frac{5}{8},1  \right] \\
C_2 &= \left[ 0, \frac{9}{64} \right] \cup \left[ \frac{15}{64}, \frac{3}{8} \right] \cup \left[ \frac{5}{8}, \frac{49}{64}  \right] \cup \left[ \frac{55}{64},1  \right] \\
C_n &= \left[ \frac{3}{8}C_{n-1} \right] \cup \left[ \frac{3}{8}C_{n-1} + \frac{5}{8}  \right] \\
\end{aligned}
$$
And where,
$$
C = \bigcap^\infty_{n=0} C_n
$$

Since the Cantor set is defined as the interesection of closed sets theorem 3.2.14 states that $C$ is closed. The compact set is also clearly bounded by $0$ and $1$. Therefore, the set is campact by the Heine Borel Theorem. \\

To prove that $C$ is perfect it is necessary to show that no point within $C$ is isolated, or in other words, every point is a limit point. Thm 3.2.5 states that $x$ is a limit point if 
$\lim x_n = x$ where $x_n$ is a sequence contained in $C$. \\

Let $x \in C$ which implies $x \in C_1$. There exists an $x_1 \in C \cup C_1$ with $x \ne X_1$ satisfiying $|x - x_1| \le 1/4$. \\

I can choose any $x \in C$ and it will be true that $x \in C_n$. Because each interval is decreasing by $(1/4)^n$. for each $n \in \mathbb{N}$ it is logical to suggest that, there exists a sequence $\{x_n : x_n \in C \cup C_n \}$ satisfying $|x - x_n| \le (1/4)^n$. \\

Because the limit exists we know that every $x \in C$ is a limit point, meaning, $C$ is perfect. 
\end{solution}

\newpage

b) Using the algorithms from section 3.1, compute the length and dimension of this cantor-like set.

\begin{solution}
If I were to scale $[0,1]$ by $8/3$ then I get the interval $[0,8/3]$. If I where to cut out the middle fourth then I get $[0,1] \cup [5/3, 8/3]$. \\

Note that multiplying by $8/3$ gives two intervals of length one. Therefore I can write, $2 = (8/3)^x$ where $x$ is the number of dimensions of the set. Solving for $x$ produces, $x = \ln{(2)}/\ln{(8/3)} \approx 0.7066951$. \\

The amount of length taken out of the set is equal to the sum of the length of one piece of the interval times by a fourth and the number of intervals being taken out. The sum is $0 + 1/4 + 3/16 + 9/64 + 27/256 + ...)$. \\

Through an infinite geometric series the sum is $\frac{1/4}{1-3/4} = \frac{1/4}{1/4} = 1$. This implies that the length of the Cantor set must be 0 because $1-1 = 0$.   
\end{solution}


