---
title: "HW #"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "4 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "3.4.9a, 4.2.2abc, 4.2.5abc"
misc: "4.2.6abcd, 4.3.1ab"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3.4.9a}

Let $\{ r_1, r_2, r_3,... \}$ be an enumeration of the rational numbers, and for each $n \in \mathbb{N}$ set $\epsilon_n = 1/2^n$. Define $O = \bigcup^\infty_{n=1} V_{\epsilon_n}(r_n)$, and let $F = O^c$.

a. Argue that $F$ is a closed, nonempty set consisting only of irrational numbers.

\begin{solution}
Demorgan's law states $(A \cup B)^c = A^c \cap B^c$. $F$ is the complement of an union, therefore it is the intersection of complements of $V_{\epsilon_n}(r_n)$. \\ 

$V_{\epsilon_n}(r_n)$ is an open set, so the complement of the neighborhood would make it a closed set. Theorem 3.2.14 states that the arbitrary intersection of closed sets is closed. This proves that $F$ is closed. \\

No rational number exists in the interval $V_{\epsilon_n}(r_n)^c$, therefore $F$ would not contain an rational numbers either. \\


The length that was removed is equal to the sum $2(1/2 + 1/4 + 1/8 + ...)$ (assuming no overlap of intervals), which by the geometric series is equal to $2\frac{1/2}{1-1/2} = 2$. \\

This means that the total length that was not included in the intersection is equal to 1. Therefore $F$ is nonempty. 
\end{solution}


<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.2.2abc}

For each stated limit, find the largest possible $\delta$-neighborhood that is a proper response to the given $\epsilon$ challenge. 

a. $\lim_{x \to 3}(5x - 6) = 9$, where $\epsilon = 1$.

\begin{solution}
Given that $\epsilon = 1$, we have:

$$
\begin{aligned}
|f(x) - L| &< \epsilon \\
|5x - 6 - 9| &< 1 \\
|5x - 15| &< 1 \\
5|x - 3| &< 1 \\
|x - 3| &< 1/5. \\
\end{aligned}
$$
It then follows that there exists a $\delta$ such that $|x - c| < \delta$. Thus I get that $|x - 3| < \delta \le 1/5$. \\

Thus (3 - 1/5, 3 + 1/5) is the largest open interval possible. 
\end{solution}


\newpage
b. $\lim_{x \to 4}\sqrt{x} = 2$, where $\epsilon = 1$.

\begin{solution}
Given that $\epsilon = 1$, we have:

$$
\begin{aligned}
|f(x) - L| &< \epsilon \\
|\sqrt{x} - 2| &< 1 \\
-1 < (\sqrt{x} - 2) &< 1 \\
1 < \sqrt{x} &< 3 \\
1 < x &< 9 \\
-3 < (x - 4) &< 5 \\
3 < |x - 4| &< 5
\end{aligned}
$$
It then follows that there exists a $\delta$ such that $|x - c| < \delta$. Thus I get that $|x - 4| < \delta \le 3$. \\

Thus (1, 7) is the largest open interval possible around 4. 
\end{solution}

c. $\lim_{x \to \pi}\lfloor x \rfloor = 3$, where $\epsilon = 1$.

\begin{solution}
Given that $\epsilon = 1$, we have:

$$
\begin{aligned}
|f(x) - L| &< \epsilon \\
| \lfloor x \rfloor - 3| &< 1 \\
-1 <( \lfloor x \rfloor - 3) &< 1 \\
2 < \lfloor x \rfloor &< 4 \\
\end{aligned}
$$
Since $x \to \pi$ I can write $2 < \lfloor x \rfloor < 4$ as,

$$
\begin{aligned}
2 < x &< 4 \\
2-\pi < (x- \pi) &< 4-\pi \\
|2-\pi| < |(x- \pi)| &< 4-\pi
\end{aligned}
$$

It then follows that there exists a $\delta$ such that $|x - c| < \delta$. Thus I get that $|x - \pi| < \delta \le |2-\pi|$.
\end{solution}



\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.2.5abc}

Use Definition 4.2.1 to supply a proper proof for the following limit statements.

a. $\lim_{x \to 2}(3x + 4) = 10$

\begin{solution}
Before the formal proof I will show how to find $\delta$. 

$$
\begin{aligned}
|f(x) - L| &< \epsilon \\
|3x + 4 - 10| &< \epsilon \\
3|x-2| &< \epsilon \\
|x-2| &< \epsilon/3
\end{aligned}
$$

Now the formal proof. 

For any $\epsilon > 0$ let $\delta = \epsilon/3$. I will show that $0 < |x-c| < \delta$ implies $|f(x) - L| < \epsilon$.

$$
\begin{aligned}
|x-2| &< \epsilon/3 \\
3|x-2| &< \epsilon \\
|3x-6| &< \epsilon \\
|(3x+4) - 10| &< \epsilon \\
|f(x) - L| &< \epsilon
\end{aligned}
$$
Thus $\lim_{x \to 2}(3x + 4) = 10$.
\end{solution}


b. $\lim_{x \to 0}x^3 = 0$

\begin{solution}
Before the formal proof I will show how to find $\delta$. 

$$
\begin{aligned}
|f(x) - L| &< \epsilon \\
|x^3 - 0| &< \epsilon \\
-\epsilon < x^3 &< \epsilon \\
-(\epsilon)^{1/3} < x &< (\epsilon)^{1/3} \\
|x| &< (\epsilon)^{1/3}
\end{aligned}
$$

Now the formal proof. 

For any $\epsilon > 0$ let $\delta = \epsilon^{1/3}$. I will show that $0 < |x-c| < \delta$ implies $|f(x) - L| < \epsilon$.

$$
\begin{aligned}
|x-0| &< \epsilon^{1/3} \\
-\epsilon^{1/3} < x &< \epsilon^{1/3} \\
-\epsilon < x^3 &< \epsilon \\
|x^3 - 0| &< \epsilon \\
|f(x) - L| &< \epsilon
\end{aligned}
$$
Thus $\lim_{x \to 0}x^3 = 0$.
\end{solution}


c. $\lim_{x \to 2}(x^2 + x - 1) = 5$

\begin{solution}
Before the formal proof I will show how to find $\delta$. 

$$
\begin{aligned}
|x^2 + x - 1 - 5| &< \epsilon \\
|x^2 + x - 6| &< \epsilon \\
|x-2||x+3| &< \epsilon
\end{aligned}
$$
We are finding the limit as $x$ approaches 2. I do not want $\delta > 1$, therefore if I choose $x=3$, then $|x + 3| \le |3 + 3| = 6 < \epsilon$, which leads to the inequality $|x+3| < \epsilon/6$ for all $x$ values close to 2, or $x \in V_1(2)$. \\

We have limited $\delta$ by 1, but it could also be smaller, depending on $\epsilon$. We can let $\delta = \min \{\epsilon/6, 1\}$.

The rest of the proof is as follows,

$$
\begin{aligned}
|x-2| &< \delta \\
|x-2| &< \epsilon/6 \\
\end{aligned}
$$
Since $|x + 3| \le = 6$

$$
\begin{aligned}
|x-2||x+3| &< (6)\frac{\epsilon}{6} \\
|(x^2 + x - 1) - 5 | &< \epsilon \\
\end{aligned}
$$
Thus, the limit is proved. 
\end{solution}


\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.2.6}
Decide if the following are true or false, and give short justifications for each conclusion.

a. If a particular $\delta$ has been constructed as a suitable response to a particular $\epsilon$ challenge, then any smaller positive $\delta$ will also suffice.

\begin{solution}
True. $\delta$ is typically the largest possible delta, so any smaller will still be within the interval set by the epsilon challenge. 
\end{solution}


b. If $\lim_{x \to a} f(x) = L$ and $a$ happens to be in the domain of $f$, then $L=f(a)$. 

\begin{solution}
False, the function could be a piece-wise function, where $f(a)$ is defined as something other than the limit. 
\end{solution}


c. If $\lim_{x \to a} f(x) = L$, then $\lim_{x \to a} 3[f(x) - 2]^2 = 3(L-2)^2$.

\begin{solution}
This is true. Since $3(L-2)^2$ is found through a limit it avoids the issue discussed in part (c). This is also supported by the algebraic limit theorem for function limits. 
\end{solution}

d. If $\lim_{x \to a} f(x) = 0$, then $\lim_{x \to a} f(x)g(x) = 0$ for any function $g$ (with domain equal to the domain of $f$.)

\begin{solution}
True. Since the domains are the same the algebraic limit theorem for functional limit applies. In which, $\lim_{x \to a} f(x)g(x) = 0 (\lim_{x \to a}g(x)) = 0$
\end{solution}



\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 05 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.3.1}

Let  $g(x) = \sqrt[3]{x}$ 

a. Prove that $g$ is continuous at $c = 0$.

\begin{solution}
$g$ is continuous at $c$ if if for all $\epsilon > 0$, there exists a $\delta > 0$ such that whenever $|x-c| < \delta$ it follows that $|f(x) - f(c)| < \epsilon$.

I will let $\delta = \epsilon^3$. Then it follows that

$$
\begin{aligned}
|x-c| &< \delta \\
|x-0| &< \epsilon^3 \\
|\sqrt[3]{x} - 0| &< \epsilon \\
|\sqrt[3]{x} - \sqrt[3]{0}| &< \epsilon \\
\end{aligned}
$$
Thus we see that $g$ is continuous at $0$.
\end{solution}

b. Prove that $g$ is continuous at a point $c \ne 0$. (The Identity $a^3 - b^3 = (a-b)(a^2 +ab + b^2)$ will be helpful.)

\begin{solution}
First to find an appropriate $\delta$ let, $|\sqrt[3]{x} - \sqrt[3]{c}| < \epsilon$

$$
\begin{aligned}
|\sqrt[3]{x} - \sqrt[3]{c}| \cdot |\frac{x^{2/3} + x^{1/3}c^{1/3} + c^{2/3}}{x^{2/3} + x^{1/3}c^{1/3} + c^{2/3}}| &< \epsilon  \\
|\frac{x-c}{x^{2/3} + x^{1/3}c^{1/3} + c^{2/3}}| &< \epsilon
\end{aligned}
$$
Note that if $x > 0$ then we get that 

$$
\begin{aligned}
|\sqrt[3]{x} - \sqrt[3]{c}| = |\frac{x-c}{x^{2/3} + x^{1/3}c^{1/3} + c^{2/3}}| < | \frac{x-c}{c^{2/3}} |  &< \epsilon \\
|\sqrt[3]{x} - \sqrt[3]{c}| < | \frac{x-c}{c^{2/3}} | &< \epsilon \\
|x-c| &< \epsilon |c^{2/3}|
\end{aligned}
$$
Now this shows that $\delta =  |c^{2/3}|$. This inequality leads to show that

$$
\begin{aligned}
|x-c| &< \epsilon |c^{2/3}| \\
| \frac{x-c}{c^{2/3}} | &< \epsilon \\
|x^{1/3} - c^{1/3}| < | \frac{x-c}{c^{2/3}} |&< \epsilon \\
|\sqrt[3]{x} - \sqrt[3]{c}| &< \epsilon \\
\end{aligned}
$$

Thus this shows that when ever $x>0$, regardless of the $c$ (positive or negative), then $g(x)$ is continuous.

Since this is an odd function, if a negative variable was entered in the function, then the result would be negative. This is the same as using positive $x$ values but multiplying by $-1$. The algebraic continuous theorem states that this product will also be continuous as well. 
\end{solution}

