---
title: "Semester Project"
author: "Jacob Jashinsky"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: false
    toc_float: false
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
library(tidyverse)
library(lubridate)
library(rgdal)
library(sp)
```

```{r load_data}
# this data was found at https://data.cityofnewyork.us/Public-Safety/Fire-Incident-Dispatch-Data/8m42-w767

Fire_Incident <- read_csv("data/Fire_Incident_Dispatch_Data.csv")
small <- sample_n(Fire_Incident, 200000)
write_csv(small, "./small.csv")
```

## Background

## Data Wrangling

```{r}
no_mfa <- Fire_Incident %>% 
  filter(INCIDENT_CLASSIFICATION_GROUP != "NonMedical MFAs", INCIDENT_CLASSIFICATION_GROUP != "Medical MFAs")

fire_count <- Fire_Incident %>%
  filter(INCIDENT_CLASSIFICATION_GROUP == c("Structural Fires", "NonStructural Fires")) %>%
  mutate(INCIDENT_DATETIME = mdy_hms(INCIDENT_DATETIME, tz = "America/New_York")) %>%
  mutate(week_day = wday(INCIDENT_DATETIME, label = TRUE)) %>% 
  group_by(INCIDENT_CLASSIFICATION_GROUP, week_day) %>%
  summarise(count = n())

emerg_count <- Fire_Incident %>%
  filter(INCIDENT_CLASSIFICATION_GROUP == c("NonMedical Emergencies", "Medical Emergencies")) %>%
  mutate(INCIDENT_DATETIME = mdy_hms(INCIDENT_DATETIME, tz = "America/New_York")) %>%
  mutate(week_day = wday(INCIDENT_DATETIME, label = TRUE)) %>% 
  group_by(INCIDENT_CLASSIFICATION_GROUP, week_day) %>%
  summarise(count = n()) %>%
  na.omit() 


dist_count <- no_mfa %>%
  group_by(INCIDENT_BOROUGH, INCIDENT_CLASSIFICATION_GROUP) %>%
  summarise(count = n())
```

## Data Visualization

```{r}
table(Fire_Incident$INCIDENT_CLASSIFICATION)

table(Fire_Incident$INCIDENT_CLASSIFICATION_GROUP)

table(Fire_Incident$INCIDENT_BOROUGH)

table(Fire_Incident$POLICEPRECINCT)

table(Fire_Incident$COMMUNITYSCHOOLDISTRICT)

table(Fire_Incident$ALARM_SOURCE_DESCRIPTION_TX)
```

```{r}
small %>%
  #filter(HIGHEST_ALARM_LEVEL != "First Alarm") %>%
ggplot() +
  geom_boxplot(aes(x = HIGHEST_ALARM_LEVEL, y = DISPATCH_RESPONSE_SECONDS_QY)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
small %>%
  #filter(HIGHEST_ALARM_LEVEL == "First Alarm") %>%
  ggplot() +
  geom_boxplot(aes(x = INCIDENT_CLASSIFICATION_GROUP, y = DISPATCH_RESPONSE_SECONDS_QY)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(small) +
  geom_boxplot(aes(x = INCIDENT_CLASSIFICATION_GROUP, y = INCIDENT_RESPONSE_SECONDS_QY, color = VALID_INCIDENT_RSPNS_TIME_INDC)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(small, aes(x = INCIDENT_CLASSIFICATION_GROUP, y = INCIDENT_TRAVEL_TM_SECONDS_QY)) +
  geom_jitter() +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
Fire_Incident %>%
  ggplot() +
  geom_boxplot(aes(x = INCIDENT_CLASSIFICATION_GROUP, y = INCIDENT_RESPONSE_SECONDS_QY)) + 
  facet_wrap(~INCIDENT_BOROUGH) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

time of day?
day of the week?


```{r}
fire_count %>%
  ggplot(aes(y = count, x = week_day, color = INCIDENT_CLASSIFICATION_GROUP)) +
    geom_point()
    #scale_y_log10() 
```

```{r}
emerg_count %>%
  ggplot(aes(y = count, x = week_day, color = INCIDENT_CLASSIFICATION_GROUP)) +
    geom_point()
    #scale_y_log10() 
```


are certian locations higher in some emergencies?

```{r}
dist_count %>%
  ggplot(aes(y = count, x = INCIDENT_BOROUGH)) +
    geom_bar(stat = "identity") +
```

```{r}
#https://www.kaggle.com/davidgibsonp/nyc-shape-file-ggplot-map

# Load shapefile 
nyc_sf <- readOGR("Shapefiles/geo_export_9dcf1f4c-6352-4820-8d5b-6aa64a32dbe0.shp")
row.names(nyc_sf) <- c("Queens", "Staten Island", "Bronx", "Brooklyn", "Manhattan")

# Plot of all NYC filled by boro
ggplot(nyc_sf) +
  aes(long,lat, group = group, fill = id) +
  geom_polygon() +
  coord_equal() 
```

school fires? 
are certains schools unsafe?

car accidents?
is one borough better than another?