---
title: "HW #9"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "2.5 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "4.4.9, 4.5.2ab"
misc: "4.5.3, 4.5.7"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.4.9}

(Lipschitz Function) A function $f: A \to \mathbb{R}$ is called Lipschitz if there exists a bound $M > 0$ such that 

$$
|\frac{f(x) - f(y)}{x-y}| \le M
$$
for all $x \ne y \in A$. Geometrically speaking, a function $f$ is Lipschitz if there is a uniform bound on the magnitude of the slopes of lines drawn through any two points in the graph of $f$.

a) Show that if $f: A \to \mathbb{R}$ is lipschitz, then it is uniformly continuous on $A$. 


\begin{solution}
Let $\epsilon > 0$ and $\delta = \epsilon/M$.

$$
\begin{aligned}
|x - y| &< \delta \\
|x - y| &< \epsilon/M \\
M|x - y| &< \epsilon \\
|f(x) - f(y)| < M|x - y| &< \epsilon \\
|f(x) - f(y)| &< \epsilon 
\end{aligned}
$$

Thus $f$ is uniformly continuous. 
\end{solution}

b) Is the converse statement true? Are all uniformly continuous functions necessarily Lipschitz?

\begin{solution}
The converse is not true. $f(x) = \sqrt{x}$ is uniformly continuous, but it is not Lipschitz.

$$
\frac{|\sqrt{x} - \sqrt{y}|}{|x-y|} = \frac{|\sqrt{x} - \sqrt{y}|}{|(\sqrt{x} - \sqrt{y})(\sqrt{x} + \sqrt{y})|} = \frac{1}{|\sqrt{x} + \sqrt{y})|}
$$
The above expression can be bounded by an $M$ except when $x=y=0$. Thus $f(x) = \sqrt{x}$ is not Lipschitz.
\end{solution}

\newpage


<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.5.2ab}

Provide an example of each of the following, or explain why the request is impossible. 

a) A continuous function defined on an open interval with range equal to a closed interval. 

\begin{solution}
Let $f(x) = 1$

This range will always be 1, which will be closed because its an isolated point.  
\end{solution}

b) A continuous function defined on a closed interval with a range equal to an open interval. 

\begin{solution}
If these intervals were bounded then by the intermediate value theorem this would be impossible. However, if you let intervals be unbounded, then we can consider $\mathbb{R}$ as a closed and open set. Therefore $f(x) = x$ is defined on a closed set and maps to an open set.    
\end{solution}


\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.5.3}

A function $f$ is increasing on $A$ if $f(x) \le f(y)$ for all $x < y$ in $A$. Show that if $f$ is increasing on $[a,b]$ and satisfies the intermediate value property (Def 4.5.3), then $f$ is continuous on $[a,b]$.

\begin{solution}
Let the function be strictly increasing on the domain, and satisfy the intermediate value property. This implies that for all $f(x) < L < f(y)$ there exist a $c$ such that $a < c < b$ and $f(c) = L$. \\ 

Characterizations of Continuity says that for all $V_\epsilon(f(c))$, there exists a $V_\delta(c)$ with the property that $x \in V_\delta(c)$ implies $f(x) \in V_\epsilon(f(c))$. \\

Because the intermediate value property is satisfied and the function is strictly increasing, then for any $\epsilon$ neighborhood around $f(c)$, it will always be possible to find a $\delta$ neighborhood around $c$. Thus the function must be continuous. 
\end{solution}



<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4.5.7}

Let $f$ be a continuous function on the closed interval $[0,1]$ with range also contained in $[0,1]$. Prove that $f$ must have a fixed point; that is, show $f(x) = x$ for at least one value of $x \in [0,1]$

\begin{solution}
I will show that $f(x) = x$ exists. \\

Since the range is contained in $[0,1]$ and by the intermediate value theorem, there exists at least one point, $c \in [0,1]$, where $f(c) = x$. \\

But since $x$ is also an element of the domain, and every element in the domain is mapped to the range. There will always exists a point $c$ in the domain such that $f(c) = c$, maps back to itself. Thus a fixed point exists. 
\end{solution}
