---
title: "HW #10"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "4.0 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "5.2.3, 5.2.5, 5.2.11"
misc: "5.3.1, 5.3.3, 5.3.7"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.2.3}

a) Use definition 5.2.1 to produce the proper formula for the derivative of $h(x) = 1/x$.

\begin{solution}
$$
\begin{aligned}
g'(c) &= \lim_{x \to c} \frac{1/x-1/c}{x-c} \\
&= \lim_{x \to c} \frac{\frac{c-x}{xc}}{x-c} \\
&= \lim_{x \to c} \frac{\frac{-(x-c)}{xc}}{x-c} \\
&= \lim_{x \to c} \frac{-1}{xc} \\
&= \frac{-1}{c^2}, \ \text{where} \ x \ne 0
\end{aligned}
$$
\end{solution}

b) Combine the result in part (a) with the Chain Rule to supply a proof for part (iv) of thm. 5.2.4



\begin{solution}
$$
\begin{aligned}
\frac{d}{dx}(f/g) &= f' \cdot \frac{1}{g} + f \cdot \left( \frac{1}{g} \right)' \\
&= \frac{f'}{g} + f \left( \frac{-1}{g^2} \right)g' \ \ (\text{after applying ther chain rule}) \\
&= \frac{f'}{g} +  \left( \frac{-f}{g^2} \right)g' \\
&= \frac{gf'}{g^2} + \frac{-fg'}{g^2} \\
&= \frac{gf'-fg'}{g^2} \\
\end{aligned}
$$
\end{solution}

\newpage

c) Supply a direct proof of thm. 5.2.4 (iv) by algebraically manipulating the difference quotient for $(f/g)$ in a style similar to the proof of thm. 5.2.4 (iii).


\begin{solution}
$$
\begin{aligned}
(f/g)'(c) &= \frac{g(c)f'(c) - f(c)g'(c)}{g(c)^2} \\
&= \lim_{x \to c} \frac{g(c)\frac{f(x)-f(c)}{x-c} - f(c)\frac{g(x)-g(c)}{x-c}}{g(c)g(x)} \\
&= \lim_{x \to c} \frac{g(c)(f(x)-f(c)) - f(c)(g(x)-g(c))}{g(c)g(x)(x-c)} \\
&= \lim_{x \to c} \frac{g(c)f(x)-g(c)f(c) - f(c)g(x)+f(c)g(c)}{g(c)g(x)(x-c)} \\
&= \lim_{x \to c} \frac{g(c)f(x) - f(c)g(x)}{g(c)g(x)(x-c)} \\
&= \lim_{x \to c} \frac{f(x)}{g(x)(x-c)} + \frac{-f(c)}{g(c)(x-c)} \\
&= \lim_{x \to c} \frac{f(x)/g(x)-f(c)/g(c)}{(x-c)} \\
\end{aligned}
$$

The result becomes the definition of a derivative. 
\end{solution}


<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.2.5}

Let 

$$
f(X=x)=\left\{
\begin{array}{ll}
      x^a \ , &  \text{if} \ x > 0  \\
      0 \ , & \text{if} \ x \le 0
\end{array} 
\right.
$$

a) For which values of $a$ is $f$ continuous at zero?

\begin{solution}
$a>0$
\end{solution}

b) For which values of $a$ is $f$ differentiable at zero? In this case, is the derivative function continuous?

\begin{solution}
$a>1$. It is continuous
\end{solution}

c) For which values of $a$ is $f$ twice-differentiable?

\begin{solution}
$a>2$
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.2.11}

Assume that $g$ is differentiable on $[a,b]$ and satisfies $g'(a) < 0 < g'(b)$.

a) Show that there exists a point $x \in (a,b)$ where $g(a) > g(x)$, and a point $y \in (a,b)$ where $g(y) < g(b)$. 

\begin{solution}
Consider $g'(a) < 0$, this means,

$$
\lim_{x \to a} \frac{g(x) - g(a)}{x-a} < 0
$$
Since $x \in (a,b)$, then $x > a$. This means that the denominator is positive. For the limit to be less than zero (negative) it must be true that $g(x) < g(a)$.

Now consider $g'(b) > 0$, which implies,

$$
\lim_{x \to b} \frac{g(x) - g(b)}{x-b} > 0
$$
Since $x \in (a,b)$, then $x < b$. This means that the denominator is negative. For the limit to be greater than zero (positive) it must be true that $g(x) < g(b)$.
\end{solution}

b) Now complete the proof of Darboux's Theorem started earlier.

\begin{solution}
The previous findings show that the set $[a,b]$ is closed and bounded. The Extreme Value Theorem then applies and shows that a minimum exists at some point $c$. \\

Now the interior Extremum theorem applies and it is known that the derivative of $g$ at $c$ is equal to zero, $g'(c) = 0$. \\

$g'(x) = f'(x) - \alpha = 0$, thus $f'(x) = \alpha$.  
\end{solution}


\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.3.1}

Recall from Exercise 4.4.9 that a function $f: A \to \mathbb{R}$ is Lipschitz on $A$ if there exists an $m > 0$ such that 

$$
\left| \frac{f(x)-f(y)}{x-y} \right| < M
$$
for all $x \ne y$ in $A$.

a) Show that if $f$ is differentiable on a closed interval $[a,b]$ and if $f'$ is continuous on $[a,b]$, then $f$ is Lipschitz on $[a,b]$. 

\begin{solution}
Since $f$ is continuous and differentiable on the closed interval, then $\left| \frac{f(x)-f(y)}{x-y} \right| = |f'(c)|$, where $c \in [a,b]$. So if $|f'(c)| \le M$ for all $c \in [a,b]$, then the function is Lipschitz \\

$f'$ is continuous so on a compact set, so the Extreme Value Theorem implies that $f'$ attains a minimum and maximum value on the interval. Let the min and max be x and y respectively. \\

Let $M = \max\{|x|, |y| \}$. There is no value of $f'$ that will exceed $M$. Therefore, $\left| \frac{f(x)-f(y)}{x-y} \right| = |f'(c)| \le M$ for all $c \in [a,b]$ and $f$ is Lipschitz.  

\end{solution}

b) Review the definition of a contractive function in Exercise 4.3.11. If we add the assumption that $|f'(x) < 1|$ on $[a,b]$, does if follow that $f$ is contractive on this set?

\begin{solution}
By definition, $f$ is a contractive function if there exists a $c$ such that $0 < c < 1$ and 
$$
|f(x) - f(y)| \le c|x - y|
$$
for all $x,y \in \mathbb{R}$ \\

Let the assumption be true.

$$
\begin{aligned}
|f'(x)| &< 1 \\
\left| \frac{f(x) - f(y)}{x-y} \right| &< 1 \\
|f(x) - f(y)| &< |x - y|
\end{aligned}
$$
Since the left is strictly less than the right, then we know that there exists a $0 < c < 1$ that will make the function contractive. 
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 05 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.3.3}

Let $h$ be a differentiable function defined on the interval $[0,3]$, and assume that $h(0) = 1$, $h(1) = 2$, and $h(3) = 2$.

a) Argue that there exists a point $d \in [0,3]$ where $h(d) = d$ 

\begin{solution}
Let $g(d) = h(d) - d$. This implies the following:

$$
\begin{aligned}
&g(0) = h(0) - 0 = 1 \\
&g(1) = h(1) - 1 = 1 \\
&g(3) = h(3) - 3 = -1 
\end{aligned}
$$

The Intermediate Value Theorem can applies because $g$ is continuous by the Algebraic continuity Theorem.    \\

This means that there exists a point $d$ such that $g(d) = 0$. \\

Since $g(d) = h(d) - d$ this implies $0 = h(d) - d$ and finally, $h(d) = d$. 
\end{solution}

b) Argue that at some point $c$ we have $h'(c) = 1/3$.

\begin{solution}
The Mean Value Theorem can apply here because the function is differentiable and continuous on the domain. \\

Consider the following,

$$
h'(c) = \frac{h(3) - h(0)}{3-0}  = \frac{2-1}{3-0} = \frac{1}{3} = h'(c)
$$
\end{solution}

c) Argue that $h'(x) = 1/4$ at some point in the domain.

\begin{solution}
Using the Mean Value Theorem again, consider the following,

$$
h'(c) = \frac{h(1) - h(0)}{1-0}  = \frac{2-1}{1-0} = 1 = h'(c)
$$
and
$$
h'(c) = \frac{h(3) - h(1)}{3-1}  = \frac{2-2}{3-1} = 0 = h'(c)
$$

The slope of the function at some point $c \in (0,1)$ is 1 but the slope of the function at some point $d \in (1,3)$ is 0. \\

Because the function is differentiable and continuous we know by Darboux Theorem that there must be a point between $c$ and $d$ such that $h'(x) = 1/4$.
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 06 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5.3.7}

A fixed point of a function $f$ is a value $x$ where $f(x) = x$. show that if $f$ is differentiable on an interval with $f'(x) \ne 1$, then $f$ can have at most one fixed point. 

\begin{solution}
We will start by assuming there are two or more fixed points at $a$ and $b$. Let $f$ be differentiable on an interval and $f'(x) \ne 1$. \\

Because $f$ is differentiable it is also continuous. The Mean Value Theorem then applies. \\

$$
\left|\frac{f(b) - f(a)}{b-a} \right| = f'(c) \\
\left|\frac{b - a}{b-a} \right| = f'(c) \\
1 = f'(c) \\
$$
However it was assumed from the beginning that $f'(x) \ne 1$. This is a contradiction.
Therefore, the function can have at most 1 fixed point. 
\end{solution}
