---
title: "Exam #3"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Jacob Jashinsky"
class: "Math 461"
hours: "3 Hours"
section: "01"
professor: "Lawrence Chilton"
due: "`r format(Sys.time(), '%B %d, %Y')`"
topic: "1,2,3"
misc: "4,5"
title-page: false
output: HomeworkBYUI::real_analysis_pdf
---
<!------------------------------------------------------------------------------>
<!------------------------------- Question 01 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{1}

Let $f,g$ and $h$ satisfy $f(x) \le g(x) \le h(x)$ for all $x$ in some domain $A$. If $\lim_{x \to c} f(x) = L$ and $\lim_{x \to c} h(x) = L$ at some point $c \in A$, use the $\epsilon - \delta$ definition of functional limits to show that $\lim_{x \to c} g(x) = L$.

\begin{solution}
Let $\epsilon > 0$. Since $\lim_{x \to c} f(x) = L$ and $\lim_{x \to c} h(x) = L$, there exists a $\delta > 0$ such that whenever $|x - c| < \delta$ implies that $|f(x) - L|< \epsilon$ and $|h(x) - L|< \epsilon$. \\

Now consider the following
$$
\begin{aligned}
f(x) \le g(x) &\le h(x) \\
f(x) - L \le g(x) - L &\le h(x) - L \\
|f(x) - L| \le |g(x) - L| &\le |h(x) - L| \\
\end{aligned}
$$
It is also true

$$
\begin{aligned}
|f(x) - L| \le |g(x) - L| \le |h(x) - L| < \epsilon \\
|g(x) - L| < \epsilon
\end{aligned}
$$
Therefore $\lim_{x \to c} g(x) = L$. 
\end{solution}

<!------------------------------------------------------------------------------>
<!------------------------------- Question 02 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{2}
Let $f$ be uniformly continuous on $\mathbb{R}$, and define a sequence of functions by $f_n(x) = f(1 + 1/n)$. Show that $f_n \to f$ uniformly on $\mathbb{R}$.


\begin{solution}
Let $f$ be uniform and $f_n(x) = f(x+1/n)$. Since $f$ is uniform there exists an $x,y \in \mathbb{R}$ such that $|y-x| < \delta$ implies that $|f(y) - f(x)| < \epsilon$ \\

Let $|y-x| < \delta$ for every $\epsilon > 0$. Further let $y = x + 1/n$. Since $f$ is continuous we can say that   

$$
\begin{aligned}
|y - x| < \delta  &\Rightarrow |f(y) - f(x)| < \epsilon \\
|x + \frac{1}{n} - x| < \delta & \Rightarrow |f(1+\frac{1}{n}) - f(x)| < \epsilon \\
|x + \frac{1}{n} - x| < \delta & \Rightarrow |f_n(x) - f(x)| < \epsilon \\
\end{aligned}
$$
Thus $(f_n) \to f$ uniformly. 

\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 03 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{3}

In section 5.4 the function 
$$
g(x) = \sum^\infty_{n=0} \frac{1}{2^n}h(2^nx)
$$
was shown to be nowhere differentiable (pg 163). Use the Weierstrass M-Test to show that $g(x)$ is continuous on $\mathbb{R}$

\begin{solution}
Using page 163 as a reference,  define $h(x) = |x|$, and let $h(x) = h(x+2)$. This implies that $h(x)$ is periodic, repeating every 2 units. \\

This also means that there is a max of $h(x)$, which is at $x=1$, and $h(1) = 1$. \\

Now, let $M_n = \frac{1}{2^n}$. Note that $\sum^\infty_{n=0} \frac{1}{2^n}$ is a converging geometric series because $r = 1/2< 1$. It is also true that $\frac{1}{2^n}h(2^nx) < M_n$ for all $n \in \mathbb{N}$. \\

The assumptions for the M-Test are now met and this implies that $\frac{1}{2^n}h(2^nx)$ converges to $g(x)$ uniformly. Theorem 6.4.2 states that because the sequence of functions is continuous and converges to $g$ uniformly, then $g(x)$ is continuous on $\mathbb{R}$. 


\end{solution}

<!------------------------------------------------------------------------------>
<!------------------------------- Question 04 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{4}

Suppose $f$ is defined and differentiable for every $x>0$, and $f'(x) \to 0$ as $x \to \infty$. Let $g(x) = f(x+1) - f(x)$. Prove that $g(x) \to 0$ as $x \to \infty$.


\begin{solution}
Since $f$ is differentiable and continuous for every $x>0$, the mean value theorem states that for a closed interval on the domain $[a,b]$, there exists a point $c \in [a,b]$ such that $f'(c) = \frac{f(b) - f(a)}{b-a}$. \\

Let $a = x$ and $b = x+1$. It follows that 
$$
\begin{aligned}
f'(c) &= \frac{f(x+1) - f(x)}{(x+1) - x}. \\
f'(c) &= f(x+1) - f(x)
\end{aligned}
$$ 

However, $g(x) = f(x+1) - f(x)$, so we know that $g(x) = f'(c)$. \\

Since $\lim_{x \to \infty} f'(x) = 0$, then $\lim_{x \to \infty} f'(c) = 0$, thus $g(x) \to 0$.  
\end{solution}

\newpage
<!------------------------------------------------------------------------------>
<!------------------------------- Question 05 ---------------------------------->
<!------------------------------------------------------------------------------>
\exercise{5}

Let $f$ be defined for all $x \in \mathbb{R}$, and suppose that $|f(x) - f(y)| \le (x-y)^2$ for all $x,y \in \mathbb{R}$. Prove that $f$ is constant. 

\begin{solution}
Let $y = c \in \mathbb{R}$, therefore we obtain the following, 

$$
\begin{aligned}
|f(x) - f(c)| &\le (x-c)^2 \\
\left| \frac{f(x) - f(c)}{x - c} \right| &\le |(x-c)|
\end{aligned}
$$

Since $f$ is defined for all $x \in \mathbb{R}$ the definition of differentiability (5.2.1) states that 

$$
f'(c) = \lim_{x \to c} \frac{f(x) - f(c)}{x - c}
$$
It follows that 

$$
\begin{aligned}
|f'(c)| &= \lim_{x \to c} \left| \frac{f(x) - f(c)}{x - c} \right| \le \lim_{x \to c}|x-c| \\
|f'(c)| &= 0  
\end{aligned}
$$
The derivative of $f$ at any point $c \in \mathbb{R}$ is zero. The derivative of a constant function is also equal to zero. Therefore, $f$ must be constant. 
\end{solution}
